user = User.create(email: "test@test.com", password: "password", password_confirmation: "password")
user2 = User.create(email: "test2@test.com", password: "password", password_confirmation: "password")

american = Restaurant.create(name: "McDonald's", address: "Chicago, IL", dress_code: "Formal", cuisine: "American", outdoor_seating: true, child_friendly: true, created_by_id: user.id, created_by_email: user.email)
chinese = Restaurant.create(name: "Yen Yen", address: "Buffalo Grove, IL", dress_code: "Casual", cuisine: "Chinese", open_bar: true, byob: true, child_friendly: true, created_by_id: user.id, created_by_email: user.email)
thai = Restaurant.create(name: "Thai Frenzy", address: "All over the place", dress_code: "Casual", cuisine: "Thai", byob: true, outdoor_seating: true, created_by_id: user.id, created_by_email: user.email)
mexican = Restaurant.create(name: "Martin's Tacos", address: "Hanover, IL", dress_code: "No Shorts", cuisine: "Mexican", outdoor_seating: true, child_friendly: true, created_by_id: user2.id, created_by_email: user2.email)
bbq = Restaurant.create(name: "Billy's BBQ", address: "Buffalo, NY", dress_code: "No Ridiculous Hats", cuisine: "BBQ", open_bar: true, created_by_id: user2.id, created_by_email: user2.email)
french = Restaurant.create(name: "Jean's Croissants", address: "Paris, France", dress_code: "Suits Only", cuisine: "French", open_bar: true, byob: true, created_by_id: user2.id, created_by_email: user2.email)

user.dishes.create(name: "Cheeseburger", price: 10, restaurant: american)
user.dishes.create(name: "Quarter Pounder", price: 6.75, restaurant: american)
user.dishes.create(name: "Big Mac", price: 10.08, restaurant: american)
user.dishes.create(name: "Kung Pao Chicken", price: 12.15, restaurant: chinese)
user.dishes.create(name: "Sweet & Sour Pork", price: 8.00, restaurant: chinese)
user.dishes.create(name: "Chop Suey", price: 5.41, restaurant: chinese)
user.dishes.create(name: "Steak Tacos", price: 6.99, restaurant: mexican)
user2.dishes.create(name: "Pad Thai", price: 7.95, restaurant: thai)
user2.dishes.create(name: "Full Rack of Ribs", price: 18.95, restaurant: bbq)
user2.dishes.create(name: "A Bag of Croissants", price: 10.95, restaurant: french)
